# server port
server:
  port: 9527

# app name
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:  # 路由配置
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates: # http://localhost:8001/payment/get/**
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_routh2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates: # 断言
            - Path=/payment/lb/**
            - After=2020-03-13T10:24:49.790+08:00[Asia/Shanghai] # CNTimeTest
            #- Cookie=username,shadow # cookie，key=username，value=shadow ；curl 请求地址 --cookie "username=shadow"
            #- Header=X-Request-Id,\d+ # 请求头要有 X-Request-Id属性并且值为正数的正则表达式
          #filters: # 过滤器
            #- AddRequestHeader=X-Request-red,blue

# 服务注册
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
